### ISSUE TITLE
PopupDirective throw error with ddc

### ISSUE THREAD

**Issue by Kleak** [dart-lang/angular_components#106]
I try to use PopupDirective with ddc but I get this error :
```
EXCEPTION: Type '_BroadcastStream<Event>' is not a subtype of type 'Stream<MouseEvent>'
STACKTRACE: 
dart:_runtime                                                                         Function.check.G
packages/angular_components/src/laminate/popup/src/popup_service.dart 75:12           PopupService.onTriggerOutsideOf
packages/angular_components/src/laminate/popup/src/popup_controller_base.dart 178:21  PopupDirective.[_addOutsideListener]
packages/angular_components/src/laminate/popup/src/popup_controller_base.dart 122:30  disposer.addStreamSubscription.async.StreamSubscription._check.dart.dsend.dart.fn.visible
packages/stack_trace/src/stack_zone_specification.dart 109:25                         <fn>.dart.fn
packages/stack_trace/src/stack_zone_specification.dart 187:14                         StackZoneSpecification.[_run]


-----async gap-----
dart:async                                                                            <fn>
packages/angular_components/src/laminate/popup/src/popup_controller_base.dart 102:49  PopupDirective.attachPopupContents
packages/angular_components/src/laminate/popup/src/popup_directive.dart 87:5          PopupDirective.attachPortal
packages/stack_trace/src/stack_zone_specification.dart 109:25                         <fn>.dart.fn
packages/stack_trace/src/stack_zone_specification.dart 187:14                         StackZoneSpecification.[_run]


-----async gap-----
dart:async                                                                                <fn>
packages/angular_components/src/laminate/popup/src/popup_directive.dart 79:24             PopupDirective.new
dart:_runtime                                                                             PopupDirective.Object
packages/angular_components/src/utils/angular/imperative_view/imperative_view.dart 120:1  Portal
packages/angular_components/src/laminate/portal/portal.dart 76:1                          TemplatePortal


-----async gap-----
dart:_runtime                                                  onValue
packages/stack_trace/src/stack_zone_specification.dart 109:25  <fn>.dart.fn
packages/stack_trace/src/stack_zone_specification.dart 187:14  StackZoneSpecification.[_run]


-----async gap-----
dart:_runtime                                          async
packages/angular2/src/core/application_ref.dart 89:27  FutureOrOfComponentRef._check.appRef.run.dart.fn

ORIGINAL EXCEPTION: Type '_BroadcastStream<Event>' is not a subtype of type 'Stream<MouseEvent>'
```

It work with dart2js, and probably in dartium (haven't test)

I have take the code from the doc :
```html
<button #openBtn (click)="isVisible = !isVisible">Toggle Popup</button>
<template popup [relativeTo]="openBtn" [(visible)]="isVisible">
  Hello World!
</template>
```

**Comment by nshahan** [comment]
Which version of the dart SDK are you using? As far as I know this should be fixed in the stable 1.24 release.

**Comment by Kleak** [comment]
Im on dev and haven't update my dart sdk today (here its 11pm). I have heard they will be a new version today will test it tomorrow and tell you if the problem persist

**Comment by Kleak** [comment]
it throw the error in 1.24 stable in fact just tested now

**Comment by Kleak** [comment]
problem is still here in Dart VM version: 1.25.0-dev.1.0 (Wed Jun 14 15:11:31 2017) on "linux_x64"

**Comment by nshahan** [comment]
OK thanks. We will investigate.

**Comment by Kleak** [comment]
Any news on this ?

**Comment by nshahan** [comment]
Sorry for the lack of update. I have a repro and I am working on a fix.

**Comment by nshahan** [comment]
There was a fix landed in the latest 0.6.0-alpha+2 release. Closing for now, please feel free to reopen if you are still experiencing issues.
